#+TITLE: Emacs configuration
#+PROPERTY: header-args :tangle init.el

* Basic configuration
#+begin_src emacs-lisp
  (setq inhibit-startup-message t)
  (menu-bar-mode -1)
  (toggle-scroll-bar -1)
  (tool-bar-mode -1)
  (tooltip-mode -1)
  (set-fringe-mode 10)
  ;; the t parameter apends to the hook, instead of prepending
  ;; this means it'd be run after other hooks that might fiddle
  ;; with the frame size
  (add-hook 'window-setup-hook 'toggle-frame-maximized t)
#+end_src
** Backup and lock
In modern compute, I do not think it's still useful to keep all these backup files and such.
#+begin_src emacs-lisp
(setq backup-inhibited t)
(setq auto-save-default nil)
#+end_src

** Packages
*** Setup straight
#+begin_src emacs-lisp
  ;; Install straight.el
  (defvar bootstrap-version)
  (let ((bootstrap-file
	 (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
	(bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
	  (url-retrieve-synchronously
	   "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
	   'silent 'inhibit-cookies)
	(goto-char (point-max))
	(eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))
(setq package-enable-at-startup nil)
#+end_src
We now force use-package to use straight.el by default
#+BEGIN_SRC emacs-lisp
  (straight-use-package 'use-package)
  (use-package straight
         :custom (straight-use-package-by-default t))
#+END_SRC
*** Babel
We will be using babel to tangle this file into an init.el file
#+BEGIN_SRC emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (python . t)))
  (setq org-confirm-babel-evaluate nil)
#+END_SRC

*** IVY, Counsel and Swiper
#+begin_src emacs-lisp
  (use-package counsel)
  (use-package ivy
    :config
    (setq ivy-use-virtual-buffers t)
    (setq ivy-count-format "(%d/%d) ")
    (ivy-mode 1)
    (global-set-key (kbd "M-x") 'counsel-M-x))
  (use-package swiper)
#+end_src

*** Whichkey
I like to have which key running to help with the binding I am not familiar with. I do not set anything particular except the threshold so it not a burden to maintain it.
#+begin_src emacs-lisp
  (use-package which-key
    :ensure t
    :config
    (setq which-key-idle-delay 0.3)
    (which-key-mode))
#+end_src

* Theme and UI
** Font
#+begin_src emacs-lisp
(set-face-attribute 'default nil :family "FiraCode Nerd Font" :height 150)
#+end_src
#+begin_src emacs-lisp
  (use-package doom-themes
  :config
  (load-theme 'doom-material t))
#+end_src
#+begin_src emacs-lisp
  (use-package doom-modeline
  :init (doom-modeline-mode 1))
#+end_src
* Evil-mode
#+begin_src emacs-lisp
  (use-package evil
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    :config
    (evil-mode 1)
    (evil-set-leader 'normal (kbd "SPC")))

  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))
#+end_src
** Global Keybindings with evil
#+begin_src emacs-lisp
  (evil-define-key 'normal 'global (kbd "<leader>bb") 'switch-to-buffer)
  (evil-define-key 'normal 'global (kbd "<leader>bk") 'kill-current-buffer)
#+end_src

* Magit
#+begin_src emacs-lisp
  (use-package magit
    :commands (magit-status))
  (evil-define-key 'normal 'global (kbd "<leader>gg") 'magit-status)
#+end_src

* TRAMP
This configuration is based on [[https://github.com/mpereira/.emacs.d][this configuration]].
#+begin_src emacs-lisp
(use-package tramp)
#+end_src
To speed up tramp from the FAQ we could either remove all version control from tramp buffer or just trim handled backend.
Version control can slow down a lot tramp buffers so we will remove them from the version control list.
#+begin_src emacs-lisp
;(setq vc-ignore-dir-regexp
;      (format "\\(%s\\)\\|\\(%s\\)"
;              vc-ignore-dir-regexp
;              tramp-file-name-regexp))
#+end_src
#+begin_src emacs-lisp
(setq vc-handled-backends '(SVN Git))
#+end_src
SSH is fast than SCP so lets use that method by default.
#+begin_src emacs-lisp
(setq tramp-default-method "ssh")
#+end_src
Try to make performance improvements with TRAMP based on [[https://github.com/syl20bnr/spacemacs/issues/11381#issuecomment-481239700][this]] and [[https://github.com/bbatsov/projectile/issues/1232#issuecomment-683449873][this]].
#+begin_src emacs-lisp
(defadvice projectile-project-root (around ignore-remote first activate)
  (unless (file-remote-p default-directory 'no-identification) ad-do-it))
#+end_src
* Projectile
#+begin_src emacs-lisp
  (use-package projectile
    :ensure t
    :init
    (projectile-mode +1)
    :config
    (setq projectile-indexing-method 'alien)
    (setq projectile-project-search-path '("~/workspace")))
    ;(projectile-mode))
  (evil-define-key 'normal 'global (kbd "<leader><SPC>") 'projectile-find-file)
  (evil-define-key 'normal 'global (kbd "<leader>pp") 'projectile-switch-project)
  (evil-define-key 'normal 'global (kbd "<leader>pb") 'projectile-switch-to-buffer)
#+end_src

* Languages setup
** Docker
#+begin_src emacs-lisp
  (use-package dockerfile-mode
  :config
  (add-to-list 'auto-mode-alist '("Dockerfile\\'" . dockerfile-mode)))
#+end_src

* Org-mode configuration
** UI improvements
#+begin_src emacs-lisp
(use-package org-bullets
  :after org
  :hook (org-mode . org-bullets-mode)
  :config
  (setq org-bullets-bullet-list '("○" "☉" "◎" "◉" "○" "◌" "◎" "●" "◦" "◯")))
#+end_src
** Structured templates
#+BEGIN_SRC emacs-lisp
  (with-eval-after-load 'org
  (require 'org-tempo)
  (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("py" . "src python")))
#+END_SRC

;; Local Variables: 
;; eval: (add-hook 'after-save-hook (lambda ()(if (y-or-n-p "Reload?")(load-file user-init-file))) nil t) 
;; eval: (add-hook 'after-save-hook (lambda ()(if (y-or-n-p "Tangle?")(org-babel-tangle))) nil t) 
;; End:
